apiVersion: v1
kind: Service
metadata:
  labels:
    name: techtrends
    env: {{ .Values.namespace.name }}
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    name: techtrends
    env: {{ .Values.namespace.name }}
  type: {{ .Values.service.type }}