apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: techtrends
    env: sandbox
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: techtrends
      env: sandbox
  template:
    metadata:
      labels:
        name: techtrends
        env: sandbox
    spec:
      containers:
      - image: gabs79/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
