apiVersion: v1
kind: Service
metadata:
  labels:
    name: techtrends
    env: sandbox
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    name: techtrends
    env: sandbox
  type: ClusterIP